config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root 'pages#home'
  get "about" => "pages#about"
  get "research" => "pages#research"
  get "learn" => "pages#learn"
  get "learn/lac" => "pages#lac"
  get "startup" => "pages#startup"
  get "lec" => "pages#lec"
  get "blog" => "pages#blog"
  get "research/seq" => "pages#seq"
  get "about/jeremywade" => "pages#jeremywade"
  get "about/isabelsalovaara" => "pages#isabelsalovaara"
  get "about/people/mukulkumar" => "pages#mukulkumar"
  get "about/careers" => "pages#careers"
  get "about/people" => "pages#people"
  get "about/partners" => "pages#partners"
  get "startupacademy" => "pages#startupacademy"
  get "bitimpact" => "pages#bitimpact"
  get "ppc" => "pages#ppc"
  get "impactislamabad" => "pages#impactislamabad"
  get "investmentforgood" => "pages#investmentforgood"
  get "impact" => "pages#impact"
  get "learn/impinv" => "pages#impinv"
  get "payment" => "pages#payment"
  get "payment/success" => "pages#success"

end

app/controllers/about_controller.rb
  class AboutController < ApplicationController
  def show
    unless params[:page].blank?
      render "about/#{params[:page].underscore}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/learn_controller.rb
  class LearnController < ApplicationController
  def show
    unless params[:page].blank?
      render "learn/#{params[:page].underscore}"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def learn
  end
  def startup
  end
  def research
  end
  def lec
  end
  def seq
  end
  def jeremywade
  end
  def isabelsalovaara
  end
  def mukulkumar
  end
  def startupacademy
  end
  def blog
  end
  def bitimpact
  end
  def ppc
  end
  def careers
  end
  def impactislamabad
  end
  def investmentforgood
  end
  def people
  end
  def impact
  end
  def lac
  end
  def impinv
  end
  def payment
  end
end

app/controllers/payment_controller.rb
  class PaymentController < ApplicationController
  def show
    unless params[:page].blank?
      render "payment/#{params[:page].underscore}"
    end
  end
end

app/controllers/research_controller.rb
  class ResearchController < ApplicationController
  def show
    unless params[:page].blank?
      render "research/#{params[:page].underscore}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
 end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_aboutheader.html.erb
 <div class="spacer-160"></div>
    <header class="product-action">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 text-left">
							<h2 class="text-white">About</h2>
							 <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#vision"><font color="#e47608">Vision</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#initiatives"><font color="#e47608">Initiatives</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team"><font color="#e47608">Team</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#location"><font color="#e47608">Location</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact"><font color="#e47608">Contact</font></a>
                    </li>
					</ul>
							<p class="text-white"></p>
						</div>
						
					</div>
				</div>

app/views/layouts/_footer.html.erb
			<footer class="short bg-secondary-4">
				<div class="container">
					<div class="row">
						<div class="col-sm-9">
							<p> Jindal Centre for Social Innovation + Entrepreneurship, O.P. Jindal Global University <p>
						</div>
							<ul class="social-icons">
								<li>
								<%= link_to "<i class=\"iicon social_facebook\"></i>".html_safe, "https://www.facebook.com/JSiEin/"-%>
							    </li>
								<li>
								<%= link_to "<i class=\"iicon social_twitter\"></i>".html_safe, "https://twitter.com/jsiein"-%>
								</li>
									<li>
								<%= link_to "<i class=\"iicon social_instagram\"></i>".html_safe, "https://www.instagram.com/jsiein/"-%>
									</li>
									
							</ul>	
						
						<div class="col-sm-3">
								<a href="https://forms.gle/72owb52aQekH7JZF7" class="btn-primary btn-filled3">Contact us</a>
						
						</div>
					</div>
				</div>
			</footer>
		</div>
				

app/views/layouts/_header.html.erb
 <div class="spacer-160"></div>
    <header class="product-action">
				<div class="container">
					<div class="row">
						<div class="col-sm-12 col-md-offset-3 text-center col-md-6">
							<h2 class="text-white">About</h2>
							 <ul class="nav navbar-nav navbar-center">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#vision"><font color="#eeeeee">Vision</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#initiatives"><font color="#eeeeee">Initiatives</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team"><font color="#eeeeee">Team</font></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#location"><font color="#eeeeee">Location</font></a>
                    </li>
                       <li>
                        <a class="page-scroll" href="#location"><font color="#eeeeee">Media</font></a>
                    </li>
                     <li>
                        <a class="page-scroll" href="#location"><font color="#eeeeee">Media</font></a>
                    </li>

                    <li>
                        <a class="page-scroll" href="#contact"><font color="#eeeeee">Contact</font></a>
                    </li>
					</ul>
							<p class="text-white"></p>
						</div>
						
					</div>
				</div>

app/views/layouts/_learnheader.html.erb
 <div class="spacer-160"></div>
        <header class="product-action">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-offset-1 text-center col-md-10">
                            <h2 class="text-white">FutureLearn Social Enterprise Program</h2>
                            <p class="text-white">Learn how to design your social enterprise model and bring it to market, and explore how to scale or sustain your social enterprise over the long term.</p>
                            <%= link_to "Join the Program", "https://www.futurelearn.com/programs/social-enterprise", :class => "btn btn-primary btn-white" %>
                            <div class="spacer-20"></div>
                        </div>
                        
                    </div>
                </div>

app/views/layouts/_nav.html.erb
<div class="nav-container">
			<nav class="top-bar centered-logo">
				<div class="container">
						<div class="col-xs-12">
					<%= link_to "http://www.jsie.in/" do %>
    				<%= image_tag 'logo.png', class: 'logo logo-dark', alt: 'JSiE'%>
					<% end %>
						<%= link_to "http://www.jsie.in/" do %>
    				<%= image_tag 'jsietext.png', class: 'logo logo-dark', alt: 'JSiE'%>
					<% end %>
					<%= link_to "http://www.jgu.edu.in/" do %>
    				<%= image_tag 'jgulogo.png', class: 'logo logo-dark-float', target: "_blank", alt: 'JGU'%>
					<% end %>
						</div>
					<div class="row utility-menu">
						<div class="col-sm-12">
							<div class="utility-inner clearfix text-center">
							<h2>
							</h2>
				
							</div>
							
						</div>
					</div>

	
					<div class="row nav-menu">
					
						<div class="col-sm-12 columns text-center">
							<ul class="menu">
								<li class="has-dropdown"><p class="text-nav1">About</p> 
									<ul class="subnav">
											    <li><%= link_to "About JSiE", "http://www.jsie.in/about" %></li>
												<li><%= link_to "Partners", "http://www.jsie.in/about/partners" %></li>
												
											</ul>

											  
								</li>
								<li class="has-dropdown"> <p class="text-nav1">Online Courses</p> 
											<ul class="subnav">
												<li><%= link_to "Impact Investing", "https://www.futurelearn.com/courses/impact-investing" %></li>
											</ul>
								</li>
								<li> <%= link_to "Research", "http://www.jsie.in/research" %></li>
								<li> <%= link_to "Impact", "http://www.jsie.in/impact" %></li>
								<li><a href="http://blog.jsie.in/" target="_blank">Blog</a></li>
								</ul>	
					
										</div>
								
								</div>
					
					<div class="mobile-toggle">
						<i class="icon icon_menu"></i>
					</div>
					
				</div>
				<div class="bottom-border"></div>
			</nav>

app/views/layouts/_researchheader.html.erb
 <div class="spacer-160"></div>
        <header class="product-action">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-offset-1 text-center col-md-10">
                            <h2 class="text-white">Research</h2>
                            <p class="text-white"></p>
                        </div>
                        
                    </div>
                </div>

app/views/layouts/_startup.html.erb
 <div class="spacer-160"></div>
        <header class="product-action">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-offset-1 text-center col-md-10">
                            <h2 class="text-white">Ready to Launch Your Startup?</h2>
                            <p class="text-white">An incubator for startups with a social mission for inclusive growth, JSiE provides pre-incubation services and entrepreneur skill development training in North India. </p>
                            <%= link_to "Apply Now", "https://jsie.typeform.com/to/sxJ86x", :class => "btn btn-primary btn-white" %>
                            <div class="spacer-20"></div>
                        </div>
                        
                    </div>
                </div>

app/views/layouts/_startupheader.html.erb
 <div id="topbar-latest-posts" class="header-widgets-wrapper">
      <div id="topbar-latest-posts-inner-fullwidth" class="hidden-sm hidden-xs">
        <div class="row">
        <div class="full-header">
                  <div class="blog-item nopadding-lr col-md-3 fade-up">
                    <div class="item-inner">
                          <%= link_to image_tag('greatidea.jpg', class: 'img-responsive', target: 'blank', alt: 'great idea'), "https://blog.jsie.in/what-problem-is-your-startup-idea-solving-e23803579d4e#.qwmh1dzhh" %>
                          <div class="header-lg-overlay">
                            <h3>A <strong>Great Startup Idea</strong></h3>
                          </div>
                        </a>                                  
                    </div>        
                  </div>
                  <div class="blog-item nopadding-lr col-md-3 fade-up">
                    <div class="item-inner">
                          <%= link_to image_tag('cofounder.jpg', class: 'img-responsive', alt: 'Cofounders'), "#" %>
                          <div class="header-lg-overlay">
                            <h3>Building Your <strong> Team</strong></h3>
                          </div>
                        </a>                                 
                    </div>        
                  </div>
                  <div class="blog-item nopadding-lr col-md-3 fade-up">
                    <div class="item-inner">
                        <%= link_to image_tag('bmc.jpg', class: 'img-responsive', alt: 'Business Model Canvas'), "#" %>
                          <div class="header-lg-overlay">
                            <h3> The<strong> Business Model</strong></h3>
                            
                          </div>
                        </a>                               
                    </div>        
                  </div>
                  <div class="blog-item nopadding-lr col-md-3 fade-up">
                    <div class="item-inner">
                          <%= link_to image_tag('traction.jpg', class: 'img-responsive', alt: 'Traction'), "#" %> 
                          <div class="header-lg-overlay">
                            <h3>Getting<strong> Traction</strong></h3>
                            
                          </div>
                        </a>                               
                    </div>        
                  </div>
        </div>
          </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Jindal Centre for Social Innovation + Entrepreneurship</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= content_for?(:head) ? yield(:head) : '' %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-161913327-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-161913327-1');
</script>
  <!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("7b20ea2fef69713584c1c32cfbe5d6e0");</script><!-- end Mixpanel -->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/bitimpact.html.erb
<%= render 'layouts/nav' %> 
 <% content_for :head do %>
  <meta property="og:url"           content="https://www.jsie.in/bitimpact" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="bitimpact: Blockchain for Social Impact" />
  <meta property="og:description"   content="An initiative at the Jindal Centre for Social Innovation & Entrepreneurship at O.P. Jindal Global University" />
  <meta property="og:image"         content="http://www.jsie.in/assets/bpact-47d81cfd99a3259379456ba13b19fb7cbb9e9040aed65f35499582a07e63736c.jpg" />
  <meta property="fb:app_id"        content="1535582636740127" />
  <% end %>
  <header class="page-header">
                <div class="background-image-holder parallax-background">
                    <%= image_tag('finance.jpg', class: 'background-image', alt: 'JSiE') %>
                </div>
                
                <div class="container">
                    <div class="row">
                        <div class="spacer-100"></div>
                        <div class="col-sm-12 text-center">
                            <h1 class="text-white space-bottom-small"><br>blockchain for social impact</h1>
                        </div>
                    </div>
                </div>
            </header>
        </div>
        <section class="duplicatable-content">
        						<div class="col-sm-12 text-center">
								<%= image_tag('bitimpacts.png', class: 'background-image', alt: 'Bitimpact') %>
							</div>
						</div>
			</section>
         <section class="pure-text-centered">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 text-center">
                            <p class="lead">
                                      Bitimpact is an innovation and impact network dedicated to supporting the implementation of blockchain technology for social impact in India. Bitimpact aims to support builders and creators of blockchain technology in maximising their positive social impact.

                            </p>
                        </div>
                    </div>
        
                </div>
            </section>
                    <section class="strip bg-primary">
                <div class="container">
                    <div class="row clearfix">
                        <div class="col-sm-12 text-center ">
                            <h3 class="text-white"><strong>Inclusion by Design. Hard-Coded. Bitimpact.</strong> <br></h3>
                            <%= link_to "Learn More", "https://medium.com/bitimpact-lab", :class => "btn btn-primary btn-white btn-filled" %>
                        </div>
                        </div>
                    </div>
                </div>
            </section>
            
            <section class="duplicatable-content">
            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <h1>Our focus</h1>
                        </div>
                    </div>
        
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="feature feature-icon-large">
                                <div class="pull-left">
                                    <i class="icon icon-genius"></i>
                                </div>
                                <div class="pull-right">
                                    <h5>Designing models and metrics for social impact</h5>
                                    <p>
                                        
                                    </p>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-sm-6">
                            <div class="feature feature-icon-large">
                                <div class="pull-left">
                                    <i class="icon icon-linegraph"></i>
                                </div>
                                <div class="pull-right">
                                    <h5>Pilot Project implementation support</h5>
                                    <p>
                                       
                                    </p>
                                </div>
                            </div>
                        </div>
                  <div class="col-sm-6">
                            <div class="feature feature-icon-large">
                                <div class="pull-left">
                                    <i class="icon icon-desktop"></i>
                                </div>
                                <div class="pull-right">
                                    <h5>Monitoring and Impact Evaluation</h5>
                                    <p>
                                    </p>
                                </div>
                            </div>
                       </div>
                        <div class="col-sm-6">
                            <div class="feature feature-icon-large">
                                <div class="pull-left">
                                    <i class="icon icon-tools-2"></i>
                                </div>
                                <div class="pull-right">
                                    <h5>Innovation Challenge Design & Judging</h5>
                                    <p>
                                      
                                    </p>
                                </div>
                            </div>
                        </div>
            </section>
            					<header class="signup"> 
					<div class="background-image-holder parallax-background">
						
					</div>
					
					<div class="container">
						<div class="row">
							<div class="col-md-10 col-md-offset-1 col-sm-12 text-center">
								<h1 class="text-white">Join us as we learn and get notified <br> about new opportunities.</h1>
							</div>
						</div>
<!-- Begin MailChimp Signup Form -->

								<div class="col-md-6 centered">
								<div class="photo-form-wrapper clearfix">
								<form action="//jsie.us9.list-manage.com/subscribe/post?u=1d9cee480d11c55b46cafda06&amp;id=9dce774ba4" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
								<input type="email" size="50" value="Enter your email" name="EMAIL" class="required email" id="mce-EMAIL" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">						
									
								<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div><div>
								<div class="col-md-6 centered">
								<input type="submit" value="Stay Updated" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary btn-filled">	
								</div>
								</form>
								</div>
								<!--End mc_embed_signup-->
								
						
						</div>
						
					</div>	
			</header>
		</div>
		 <%= render 'layouts/footer' %>
	    <script> mixpanel.track("bitimpact");</script>	

app/views/pages/lec.html.erb
<%= render 'layouts/nav' %>
<div class="main-container">
	
	<header class="signup"> 
					<div class="background-image-holder parallax-background">
						
					</div>
					
					<div class="container">
						<div class="row">
							<div class="col-md-10 col-md-offset-1 col-sm-12 text-center">
								<h1 class="text-white">Legal Entrepreneurship Cell<br>Student-Initiative of JSiE</h1>
							</div>
						</div>
<!-- Begin MailChimp Signup Form -->

								<div class="col-md-6 centered">
								<div class="photo-form-wrapper clearfix">
								<form action="//jsie.us9.list-manage.com/subscribe/post?u=1d9cee480d11c55b46cafda06&amp;id=42950bbb79" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
								<input type="email" size="50" value="Enter your email" name="EMAIL" class="required email" id="mce-EMAIL" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">						
									
								<div id="mce-responses" class="clear">
								<div class="response" id="mce-error-response" style="display:none"></div>
								<div class="response" id="mce-success-response" style="display:none"></div><div>
								<div class="col-md-6 centered">
								<input type="submit" value="Get Legal Updates" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary btn-filled">	
								</div>
								</form>
								</div>
								<!--End mc_embed_signup-->
								
						
						</div>
						
					</div>	
			</header>
					
						
			
		<section id="contact">
<div class="typeform-widget" data-url="https://jsie.typeform.com/to/eD0w5X" data-text="Contact Form" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script></section>
 <%= render 'layouts/footer' %>

app/views/pages/people.html.erb
<%= render 'layouts/nav' %> 
<% content_for :head do %>
  <meta property="og:url"           content="https://www.jsie.in/about/people" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="People | JSiE" />
  <meta property="og:description"   content="The Jindal Centre for Social Innovation + Entrepreneurship at O.P. Jindal Global University" />
  <meta property="og:image"         content="http://www.jsie.in/assets/impact1-bef86849769a8abc77b09d57364608b2e861ede29e2feca2fe795faeb5ad1348.png" />
  <meta property="fb:app_id"        content="1535582636740127" />
  <% end %>
   <header class="page-header1">
                <div class="background-image-holder parallax-background">
                    <%= image_tag('backgroundblue.png', class: 'background-image', alt: 'JSiE') %>
                </div>
              </header>
                    <section class="text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="feature feature-9">    
                                <%= link_to about_jeremywade_path do %>
                                <%= image_tag('jwade.jpg', class: 'background-image', alt: 'Jeremy Wade') %>
                                <% end %>
                                <h2>Jeremy Wade</h2> <p class="text-center">Founding Director, JSiE</p> 
                                  <div class="spacer-10"></div>
                              </div>
                        </div>
                         <div class="col-sm-8">
                            <p class="lead">
                  <b>Jeremy founded the Jindal Centre for Social Innovation + Entrepreneurship in 2014. Jeremy is an Associate Professor of Practice at the Jindal Global Business School, O.P. Jindal Global University.</b> An online course creator and educator,  over 50,000 students from 159 countries have enrolled in his online courses on sustainable business and impact investing. Since 2015, Jeremy has led the incubation program for Tibetan refugee entrepreneurs living in India in partnership with the Central Tibetan Administration. Jeremy has published articles in the Journal of Social Entrepreneurship, Journal of Small Business & Entrepreneurship, and Diaspora, Indigenous, and Minority Education. </p>  

                  <p class="lead">
                  Originally from the United States, he began his career at the U.S. Department of the Treasury, where he helped supervise a portfolio of financial institutions in the aftermath of the Global Financial Crisis from 2008-2012.

                </p>


                </div>
              </div>
                   <div class="spacer-40"></div>

                              <div class="spacer-40"></div>
                      <section class="strip bg-primary">
                      <div class="container">
                     <div class="row clearfix">
                   <div class="col-xs-12">
                   <h2 class="text-white"><strong>Fellows</strong></h2>
            </div>
          </div>
        </div>
      </section>
       <div class="spacer-40"></div>
      <div class="row">

                              <div class="col-sm-3">
                             <div class="feature feature-9"> 
                                <%= image_tag('ron.jpg', alt: 'Ronita Choudhuri') %>
                                <h2>Ronita Choudhuri</h2> <p class="text-center">Assistant Professor of Practice<br> Jindal Global Business School</p> 
                                <div class="spacer-10"></div></div>
                            </div>
                             <div class="row">
                                      <div class="spacer-40"></div>
                      <section class="strip bg-primary">
                      <div class="container">
                     <div class="row clearfix">
                   <div class="col-xs-12">
                   <h2 class="text-white"><strong>Research Assistants</strong></h2>
            </div>
          </div>
        </div>
      </section>
       <div class="spacer-40"></div>
                         <div class="col-sm-3">
                             <div class="feature feature-9"> 
                               <%= image_tag('shine.jpg', alt: 'Shine Varghese') %>
                                <h2>Shine Varghese</h2>
                                <p class="text-center">Coordinator, Startup JGU</p>
                                  <div class="spacer-10"></div>
                            </div>
                        </div>
                        
                         <div class="col-sm-3">
                           <div class="feature feature-9"> 
                                <%= image_tag('aditya.jpg', alt: 'Aditya Dey') %>
                                <h2>Aditya Dey </h2>
                                <p class="text-center">Research Assistant</p>  
                                <div class="spacer-10"></div>
                            </div>
                        </div>
                      
                  
                   </div>
                    </div>
                    
                </div>
                    
                </div>
            </section>
		</div>
        <%= render 'layouts/footer' %>
        <script> mixpanel.track("people");</script> 